{
"ILYSTARX":
{"Moves":["Leaf Shield","Leaf Blade","Zen Headbutt","Agility"],
"PokemonName":"Chlorofin",
"Nature":"Modest",
"Nickname":"My Star",
"Pokeball":"Divine Berry",
"Level":30,
"Gender":"Female",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"Happy Birthday Star <3!",
"EVs":{"SpA":16,"HP":16,"Speed":16,"SpD":16,"Def":16,"Atk":16},
"BadgeLock":2,
"Allowed":true
},

"23RDBIRTHDAY":
{"Moves":["Meteor Tomb","Recover","Hypnosis","Aqua Tail"],
"PokemonName":"Xotec",
"Nature":"Modest",
"Nickname":"Elena",
"Pokeball":"Divine Berry",
"Level":25,
"Gender":"Female",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"Happy 23rd birthday, Elena!",
"EVs":{"SpA":16,"HP":16,"Speed":16,"SpD":16,"Def":16,"Atk":16},
"BadgeLock":2,
"Allowed":false
},
"CHRISTMAS2023":
{"Moves":["Emulate","Recover"],
"PokemonName":"Duplicat",
"Nature":"Modest",
"Nickname":"X-MAS 2023",
"Pokeball":"Divine Berry",
"Level":45,
"Gender":"Female",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"Santa's cat",
"EVs":{"SpA":16,"HP":16,"Speed":16,"SpD":16,"Def":16,"Atk":16},
"BadgeLock":3,
"Allowed":false
},
"SUMMER VIBES":
{"Moves":["Dragon Breath","Venoshock","Double Team","Amnesia"],
"PokemonName":"Glauqua",
"Nature":"Quirky",
"Nickname":"ZERO2HERO",
"Pokeball":"Divine Berry",
"Level":35,
"Gender":"Female",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"minex",
"EVs":{"SpA":16,"HP":16,"Speed":16,"SpD":16,"Def":16,"Atk":16},
"BadgeLock":2,
"Allowed":false
},
"FREENOM":
{"Moves":["Confusion","Sing","Double Team","Wing Attack"],
"PokemonName":"Eshouten",
"Nature":"Quirky",
"Nickname":"Freenom",
"Pokeball":"Divine Berry",
"Level":35,
"Gender":"Female",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"minex",
"EVs":{"SpA":16,"HP":16,"Speed":16,"SpD":16,"Def":16,"Atk":16},
"BadgeLock":2,
"Allowed":false
},
"ALPHA":
{"Moves":["Fusion Flare","Blue Flare","Recover","Flamethrower"],
"PokemonName":"Red Puffle",
"Nature":"Timid",
"Nickname":"ALPHA",
"Pokeball":"Pokeball",
"Level":30,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"minex",
"EVs":{"SpA":16,"HP":16,"Speed":16,"SpD":16,"Def":16,"Atk":16},
"BadgeLock":2,
"Allowed":false
},
"CRANEVIEW":
{"Moves":["Dragon Claw","Slam","Recover","Dragon Pulse"],
"PokemonName":"Tracton",
"Nature":"Timid",
"Nickname":"Crane",
"Pokeball":"Divine Berry",
"Level":40,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"minex",
"EVs":{"SpA":16,"HP":16,"Speed":16,"SpD":16,"Def":16,"Atk":16},
"BadgeLock":3,
"Allowed":true
},
"DESOLATION":
{"Moves":["Solar Beam","Flamethrower","Recover","Dragon Pulse"],
"PokemonName":"Ornitherb",
"Nature":"Timid",
"Nickname":"DESOLE",
"Pokeball":"Divine Berry",
"Level":40,
"Gender":"Random",
"Shiny":false,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"minex",
"EVs":{"SpA":16,"HP":16,"Speed":16,"SpD":16,"Def":16,"Atk":16},
"BadgeLock":3,
"Allowed":true
},
"CuteFox":
{"Moves":["Scratch"],
"PokemonName":"Fennekin",
"Nature":"Timid",
"Nickname":"Fennekin",
"Pokeball":"Master Ball",
"Level":15,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":1,
"Allowed":false
},
"Summer Time":
{"Moves":["Quick Attack","Protect"],
"PokemonName":"Eevee",
"Nature":"Timid",
"Nickname":"Eevee",
"Pokeball":"Pokeball",
"Level":30,
"Gender":"Random",
"Shiny":true,
"Form":"Summer",
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"Special Limited",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
},
"SparkleFish":
{"Moves":["Ice Beam"],
"PokemonName":"Feebas",
"Nature":"Timid",
"Nickname":"Feebas",
"Pokeball":"Master Ball",
"Level":15,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":1,
"Allowed":false
},
"ShinyBunBun":
{"Moves":["Shadow Ball"],
"PokemonName":"Lopunny",
"Nature":"Timid",
"Nickname":"Lopunny",
"Pokeball":"Master Ball",
"Level":15,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":1,
"Allowed":false
},
"BlueFlame":
{"Moves":["Fire Blast"],
"PokemonName":"Ponyta",
"Nature":"Timid",
"Nickname":"Ponyta",
"Pokeball":"Master Ball",
"Level":15,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":1,
"Allowed":false
},
"BigBird":
{"Moves":["Dragon Claw"],
"PokemonName":"Altaria",
"Nature":"Timid",
"Nickname":"Altaria",
"Pokeball":"Master Ball",
"Level":15,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":1,
"Allowed":false
},
"PlatinumBird":
{"Moves":["Brave Bird"],
"PokemonName":"Corviknight",
"Nature":"Timid",
"Nickname":"Corviknight",
"Pokeball":"Master Ball",
"Level":15,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":1,
"Allowed":false
},
"YellowHearts":
{"Moves":["Hyper Voice"],
"PokemonName":"Luvdisc",
"Nature":"Timid",
"Nickname":"Luvdisc",
"Pokeball":"Master Ball",
"Level":15,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":1,
"Allowed":false
},
"GreatestBall":
{"Moves":["Explosion"],
"PokemonName":"Electrode",
"Nature":"Timid",
"Nickname":"Electrode",
"Pokeball":"Master Ball",
"Level":15,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":1,
"Allowed":false
},
"IrateDragon":
{"Moves":["Crunch"],
"PokemonName":"Deino",
"Nature":"Timid",
"Nickname":"Deino",
"Pokeball":"Master Ball",
"Level":15,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":1,
"Allowed":false
},
"AxeDragon":
{"Moves":["Crunch"],
"PokemonName":"Fraxure",
"Nature":"Timid",
"Nickname":"Fraxure",
"Pokeball":"Master Ball",
"Level":15,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":1,
"Allowed":false
},
"Valentines2022":
{"Moves":["Twister"],
"PokemonName":"Latias",
"Nature":"Timid",
"Nickname":"Latias",
"Pokeball":"Master Ball",
"Level":15,
"Gender":"Random",
"Shiny":true,
"Form":"Valentines",
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":1,
"Allowed":false
},
"Christmas2021":
{"Moves":["Swords Dance", "Close Combat", "Stone Edge", "Protect"],
"PokemonName":"Virizion",
"Nature":"Jolly",
"Nickname":"Virizion",
"Pokeball":"Master Ball",
"Level":50,
"Gender":"Random",
"Shiny":true,
"Form":"Christmas",
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":1,
"Allowed":false
},
"Headbutt":
{"Moves":["Head Smash"],
"PokemonName":"Rampardos",
"Nature":"Timid",
"Nickname":"Rampardos",
"Pokeball":"Master Ball",
"Level":15,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":1,
"Allowed":false
},
"EonOne":
{"Moves":["Draco Meteor"],
"PokemonName":"Latias",
"Nature":"Timid",
"Nickname":"Latias",
"Pokeball":"Master Ball",
"Level":30,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":3,
"Allowed":false
},
"WishfulThinking":
{"Moves":["V-Create", "Fire Punch", "Iron Head", "Protect"],
"PokemonName":"Jirachi",
"Nature":"Jolly",
"Nickname":"Jirachi",
"Pokeball":"Master Ball",
"Level":30,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":3,
"Allowed":false
},
"Shinies":
{"Moves":["Shadow Ball"],
"PokemonName":"Mew",
"Nature":"Jolly",
"Nickname":"Mew",
"Pokeball":"Master Ball",
"Level":30,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":3,
"Allowed":false
},
"EonTwo":
{"Moves":["Draco Meteor"],
"PokemonName":"Latios",
"Nature":"Timid",
"Nickname":"Latias",
"Pokeball":"Master Ball",
"Level":30,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":3,
"Allowed":false
},
"GoCrayzee":
{"Moves":["Flamethrower"],
"PokemonName":"Incineroar",
"Nature":"Timid",
"Nickname":"Incineroar",
"Pokeball":"Pokeball",
"Level":15,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":30,"SpD":31,"Def":31,"Atk":31},
"OT":"GoCrayzee",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
},
"MrMarvin":
{"Moves":["Flamethrower"],
"PokemonName":"Tepig",
"Nature":"Timid",
"Nickname":"Tepig",
"Pokeball":"Pokeball",
"Level":15,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":30,"SpD":31,"Def":31,"Atk":31},
"OT":"GoCrayzee",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
},
"Sub2GoCrayzee":
{"Moves":["Tackle"],
"PokemonName":"Eevee",
"Nature":"Timid",
"Nickname":"Eevee",
"Pokeball":"Pokeball",
"Level":15,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":30,"SpD":31,"Def":31,"Atk":31},
"OT":"GoCrayzee",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
},
"Fullmoon":
{"Moves":["Moonblast"],
"PokemonName":"Lunala",
"Nature":"Timid",
"Nickname":"Lunala",
"Pokeball":"Pokeball",
"Level":15,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":30,"SpD":31,"Def":31,"Atk":31},
"OT":"Mystery Gift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
},
"Morningsun":
{"Moves":["Sunsteel Strike"],
"PokemonName":"Solgaleo",
"Nature":"Timid",
"Nickname":"Solgaleo",
"Pokeball":"Pokeball",
"Level":15,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":30,"SpD":31,"Def":31,"Atk":31},
"OT":"Mystery Gift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
},
"TinTower":
{"Moves":["Sacred Fire"],
"PokemonName":"Ho-Oh",
"Nature":"Timid",
"Nickname":"Ho-Oh",
"Pokeball":"Pokeball",
"Level":15,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":30,"SpD":31,"Def":31,"Atk":31},
"OT":"Mystery Gift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
},
"WhirlIsland":
{"Moves":["Aeroblast"],
"PokemonName":"Lugia",
"Nature":"Timid",
"Nickname":"Lugia",
"Pokeball":"Pokeball",
"Level":15,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":30,"SpD":31,"Def":31,"Atk":31},
"OT":"Mystery Gift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
},
"PartnerEevee":
{"Moves":["Tackle"],
"PokemonName":"Eevee",
"Nature":"Timid",
"Nickname":"Eevee",
"Pokeball":"Pokeball",
"Level":5,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":30,"SpD":31,"Def":31,"Atk":31},
"OT":"Mystery Gift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
},
"Free Rayquaza":
{"Moves":["Earthquake","Ice Beam","Extreme Speed","Draco Meteor"],
"PokemonName":"Rayquaza",
"Nature":"Timid",
"Nickname":"Rayquaza",
"Pokeball":"Master Ball",
"Level":80,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":8,
"Allowed":false
},
"Defeated Nuzlocke":
{"Moves":["Earthquake","Ice Beam","Extreme Speed","Draco Meteor"],
"PokemonName":"Rayquaza",
"Nature":"Timid",
"Nickname":"Rayquaza",
"Pokeball":"Master Ball",
"Level":80,
"Gender":"Random",
"Shiny":true,
"HeldItem":"Rayquazite",
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"Nuzlocke Completed",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
},
"Shadow":
{"Moves":["Calm Mind","Shadow Ball","Recover","Aeroblast"],
"PokemonName":"Lugia",
"Nature":"Timid",
"Nickname":"Shadow Lugia",
"Pokeball":"Master Ball",
"Level":50,
"Gender":"Random",
"Shiny":false,
"Form":"Shadow",
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":5,
"Allowed":false
},
"StrikesBack":
{"Moves":["Calm Mind","Shadow Ball","Recover","Psychic"],
"PokemonName":"Mewtwo",
"Nature":"Timid",
"Nickname":"Mewtwo",
"Pokeball":"Master Ball",
"Level":80,
"Gender":"Random",
"Shiny":false,
"Form":"Cyborg",
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":8,
"Allowed":false
},
"Moonbeamers":
{"Moves":["Shadow Ball"],
"PokemonName":"Darkrai",
"Nature":"Timid",
"Nickname":"Darkrai",
"Pokeball":"Master Ball",
"Level":30,
"Gender":"Random",
"Shiny":true,
"Form":"Moonlight",
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"m00ntvxTTV",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":5,
"Allowed":false
},
"Synthetic":
{"Moves":["Fire Blast","Thunder Punch","Dragon Dance","Aerial Ace"],
"PokemonName":"Charizard",
"Nature":"Jolly",
"Nickname":"Syn-Charizard",
"Pokeball":"Pokeball",
"Level":50,
"Gender":"Random",
"Shiny":true,
"Form":"Syn",
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":5,
"Allowed":false
},
"Zekroom":
{"Moves":["Earth Power","Thunder","Draco Meteor","Bolt Strike"],
"PokemonName":"Zekrom",
"Nature":"Timid",
"Nickname":"Zekrom",
"Pokeball":"Pokeball",
"Level":85,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":8,
"Allowed":false
},
"Monochrome":
{"Moves":["Double Team","Foul Play","Toxic","Protect"],
"PokemonName":"Umbreon",
"Nature":"Timid",
"Nickname":"Umbreon",
"Pokeball":"Pokeball",
"Level":10,
"Gender":"Random",
"Shiny":true,
"Form":"Monochrome",
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":1,
"Allowed":false
},
"Surfboi":
{"Moves":["Surf","Nasty Plot","Thunderbolt","Thunder"],
"PokemonName":"Pikachu",
"Nature":"Timid",
"Nickname":"Pikachu",
"Pokeball":"Pokeball",
"Level":10,
"Gender":"Random",
"Shiny":true,
"Form":"Surfing",
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":1,
"Allowed":false
},
"World":
{"Moves":["Quick Attack","Nasty Plot","Thunderbolt","Thunder"],
"PokemonName":"Pikachu",
"Nature":"Timid",
"Nickname":"Pikachu",
"Pokeball":"Pokeball",
"Level":50,
"Gender":"Random",
"Shiny":true,
"Form":"World",
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":3,
"Allowed":false
},
"Pikacheese":
{"Moves":["Discharge","Thunder Punch","Light Screen","Nasty Plot"],
"PokemonName":"Pikachu",
"Nature":"Timid",
"Nickname":"Pikachu",
"Pokeball":"Pokeball",
"Level":45,
"Gender":"Random",
"Shiny":true,
"Form":"Classic",
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":4,
"Allowed":false
},
"Free Mewtwo":
{"Moves":["Psychic","Recover","Swift","Shadow Ball"],
"PokemonName":"Mewtwo",
"Nature":"Timid",
"Nickname":"Mewtwo",
"Pokeball":"Master Ball",
"Level":80,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"BadgeLock":8,
"Allowed":false
},
"EeveeInSparkle":
{"Moves":["Toxic","Double Team","Tackle","Swift"],
"PokemonName":"Eevee",
"Nature":"Timid",
"Nickname":"Eevee",
"Pokeball":"Master Ball",
"Level":5,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
},
"Ultima":
{"Moves":["Toxic","Double Team","Tackle","Swift"],
"PokemonName":"Umbreon",
"Nature":"Timid",
"Nickname":"Ultima",
"Pokeball":"Master Ball",
"Level":10,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"Project:Ultima",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
},
"Thanksgiving":
{"Moves":["Sacred Fire","Ember","Recover"],
"PokemonName":"Ho-Oh",
"Nature":"Timid",
"Nickname":"Ho-Oh",
"Pokeball":"Master Ball",
"Level":50,
"Gender":"Random",
"Shiny":true,
"Form":"Turkey",
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"Happy Thanksgiving",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
},
"Christmas":
{"Moves":["Blizzard","Ice Beam"],
"PokemonName":"Articuno",
"Nature":"Timid",
"Nickname":"Articuno",
"Pokeball":"Master Ball",
"Level":50,
"Gender":"Random",
"Shiny":true,
"Form":"Christmas",
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"Happy Holidays",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
},
"SantaHat":
{"Moves":["V-Create"],
"PokemonName":"Jirachi",
"Nature":"Timid",
"Nickname":"Jirachi",
"Pokeball":"Master Ball",
"Level":30,
"Gender":"Random",
"Shiny":true,
"Form":"Christmas",
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"Happy Holidays",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
},
"Freeze":
{"Moves":["Blizzard"],
"PokemonName":"Zapdos",
"Nature":"Timid",
"Nickname":"Zapdos",
"Pokeball":"Master Ball",
"Level":30,
"Gender":"Random",
"Shiny":true,
"Form":"Freeze",
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"Mystery Gift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
},
"Sea":
{"Moves":["Hydro Pump"],
"PokemonName":"Moltres",
"Nature":"Timid",
"Nickname":"Moltres",
"Pokeball":"Master Ball",
"Level":30,
"Gender":"Random",
"Shiny":true,
"Form":"Sea",
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"Mystery Gift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
},
"Flame":
{"Moves":["Fire Blast"],
"PokemonName":"Articuno",
"Nature":"Timid",
"Nickname":"Articuno",
"Pokeball":"Master Ball",
"Level":30,
"Gender":"Random",
"Shiny":true,
"Form":"Flame",
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"Mystery Gift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
},
"Delta":
{"Moves":["Close Combat"],
"PokemonName":"Lucario",
"Nature":"Timid",
"Nickname":"Lucario",
"Pokeball":"Master Ball",
"Level":30,
"Gender":"Random",
"Shiny":false,
"Form":"Delta",
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"Mystery Gift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
},
"GreenEyes":
{"Moves":["Sing"],
"PokemonName":"Jigglypuff",
"Nature":"Timid",
"Nickname":"Jigglypuff",
"Pokeball":"Master Ball",
"Level":30,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
},
"Goobruh":
{"Moves":["Dragon Claw"],
"PokemonName":"Goodra",
"Nature":"Timid",
"Nickname":"Goodra",
"Pokeball":"Master Ball",
"Level":30,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
},
"Glitch":
{"Moves":["Tri Attack"],
"PokemonName":"Porygon",
"Nature":"Timid",
"Nickname":"Porygon",
"Pokeball":"Master Ball",
"Level":30,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
},
"DarkDog":
{"Moves":["Crunch"],
"PokemonName":"Houndoom",
"Nature":"Hasty",
"Nickname":"Houndoom",
"Pokeball":"Master Ball",
"Level":30,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
},
"Crimson":
{"Moves":["Night Slash"],
"PokemonName":"Absol",
"Nature":"Jolly",
"Nickname":"Absol",
"Pokeball":"Master Ball",
"Level":30,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
},
"RedSonic":
{"Moves":["Slash"],
"PokemonName":"Sandslash",
"Nature":"Adamand",
"Nickname":"Sandslash",
"Pokeball":"Master Ball",
"Level":30,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
},
"17kMembers":
{"Moves":["Earthquake"],
"PokemonName":"Metagross",
"Nature":"Timid",
"Nickname":"Metagross",
"Pokeball":"Master Ball",
"Level":30,
"Gender":"Random",
"Shiny":false,
"Form":"Ancient",
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"MysteryGift",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
},
"Dialga":
{"Moves":["Earth Power","Aura Sphere","Roar of Time","Flash Cannon"],
"PokemonName":"Dialga",
"Nature":"Timid",
"Nickname":"Dialga",
"Pokeball":"Master Ball",
"Level":100,
"Gender":"Random",
"Shiny":true,
"TL":true,
"IVs":{"SpA":31,"HP":31,"Speed":31,"SpD":31,"Def":31,"Atk":31},
"OT":"Owner",
"EVs":{"SpA":0,"HP":0,"Speed":0,"SpD":0,"Def":0,"Atk":0},
"Allowed":false
}
}
